COLUMNS:
  id: int64
  age: float64
  bp: float64
  sg: float64
  al: float64
  su: float64
  rbc: object
  pc: object
  pcc: object
  ba: object
  bgr: float64
  bu: float64
  sc: float64
  sod: float64
  pot: float64
  hemo: float64
  pcv: object
  wc: object
  rc: object
  htn: object
  dm: object
  cad: object
  appet: object
  pe: object
  ane: object
  classification: object

TARGET_COLUMN:
  name: classification
